name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["type: feature", "status: needs-info"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Currently, users cannot... This causes...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you implement this feature?
      placeholder: I suggest adding...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: I also thought about...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Must have (critical for launch)
        - Should have (important but not critical)
        - Nice to have (enhance UX)
        - Future consideration
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application would this affect?
      options:
        - Authentication
        - CV Intelligence
        - Interview Coordinator
        - Support Tickets
        - Analytics Dashboard
        - Admin Panel
        - New Module
        - Other
    validations:
      required: true

  - type: textarea
    id: user-impact
    attributes:
      label: User Impact
      description: Who would benefit from this feature and how?
      placeholder: This would help [persona] by...
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Effort Estimate
      description: How complex do you think this feature is?
      options:
        - Small (< 1 day)
        - Medium (1-3 days)
        - Large (> 3 days)
        - Unknown
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Designs
      description: If you have mockups or design ideas, please share them
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references
    validations:
      required: false
