name: 📖 User Story
description: Create a user story for development
title: "[Story]: "
labels: ["type: feature", "status: ready"]
body:
  - type: markdown
    attributes:
      value: |
        User stories help us understand features from the user's perspective.

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Write the user story in the format - As a [persona], I want [goal], so that [benefit]
      placeholder: |
        As a **hiring manager**,
        I want **to receive email reminders before interviews**,
        so that **I never miss scheduled meetings**.
    validations:
      required: true

  - type: dropdown
    id: persona
    attributes:
      label: User Persona
      description: Which user persona is this for?
      options:
        - HR Manager
        - Recruiter
        - Hiring Manager
        - Interview Coordinator
        - Admin/Superadmin
        - Job Candidate
        - Other
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define the criteria that must be met for this story to be complete
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Implementation details, dependencies, potential challenges
      placeholder: |
        - Database changes needed
        - API endpoints required
        - Dependencies on other features
    validations:
      required: false

  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: When is this story considered complete?
      placeholder: |
        - [ ] Code written and reviewed
        - [ ] Tests pass
        - [ ] Documentation updated
        - [ ] Deployed to staging
        - [ ] Tested by QA/user
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this story?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Story Points / Effort
      description: Estimate the effort required
      options:
        - 1 (XS - few hours)
        - 2 (S - half day)
        - 3 (M - 1 day)
        - 5 (L - 2-3 days)
        - 8 (XL - 1 week)
        - 13 (XXL - needs breakdown)
    validations:
      required: false

  - type: input
    id: epic
    attributes:
      label: Epic/Feature
      description: Which larger feature or epic does this belong to?
      placeholder: "#123 - Email Notification System"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other context, designs, or references
    validations:
      required: false
